name: Docker Image CI

env:
  ACT: debug

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:    # Ermöglicht manuelles Auslösen über die GitHub-Oberfläche
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write  # Erlaubt das Pushen zu GHCR
    
    steps:
      - name: Debug variables
        run: |
          echo "Registry: ghcr.io"
          echo "Username: ${{ github.actor }}"
          echo "Repository: ${{ github.repository }}"
      
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TESTTOKEN }}

      - name: Build and push Docker image
        run: |
          docker build . --file Dockerfile --tag ghcr.io/widukind42/ytdlp_debian:latest 
          docker push ghcr.io/widukind42/ytdlp_debian:latest

      - name: Container starten und Skript ausführen (Debian)
        run: |
          podman run --rm \
            -v "$(pwd):/data:z" \
            --entrypoint /bin/sh \
            ghcr.io/widukind42/ytdlp_debian \
            ./.github/scripts/show-container-releases.sh >> ./PackageInventory.md

      - name: Änderungen commiten
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./PackageInventory.md
          git commit -m "Update release info [skip ci]"
          git push
